### ISSUE TITLE
Why use Mason and Lazy?

### ISSUE THREAD

**Issue by AlexLJordan** [tokiory/neovim-boilerplate#1]
Hey! Thanks for creating this repo, I'm just starting to dive deeper into (N)Vim; so this is a great help!

Why do you use two package managers, mason and lazy, in this config? Shouldn't one manager be enough?

Thanks!

**Comment by tokiory** [comment]
Hello! In this configuration, only lazy.nvim is used, packer was previously available, and perhaps references to it remained in README.md

- `packer.nvim` - was previously a manager for plugins
- `lazy.nvim` - current manager for plugins. Essentially, it controls which plugins need to be downloaded and connected

**mason.nvim** is an LSP manager, it downloads the necessary files for LSP and DAP to work. It has nothing to do with managing plugins inside Neovim; rather, on the contrary, it relates to managing other programs (LSPs) that may be needed in Neovim

It would be nice to mention this in the README) I'll do it later🙏

**Comment by AlexLJordan** [comment]
Understood!
Thanks for answering!
