### ISSUE TITLE
Add nodejs and golang as dependencies. 

### ISSUE THREAD

**Issue by Abrolhus** [tokiory/neovim-boilerplate#3]
Hi, how are you?
Can you please add both node js and Go language as dependencies to the boilerplate? I tried to install it on a new ubuntu 23.10 computer without this packeges and it didnt work properly.

**Comment by Abrolhus** [comment]
Thanks for the project anyway, im rebuilding my config starting from this one!

**Comment by tokiory** [comment]
Fixed, thx for your attention)
